### ISSUE TITLE
Editor-spesifike ting i prosjekt-gitignore

### ISSUE THREAD

**Issue by ludvigsj** [laafte/lafteweb#11]
https://github.com/henninghalv/laafteweb/blob/c6689d0094ddb90466f782e8f08b821172bb3b4b/.gitignore#L4-L13

Dette bør bo i global gitignore lokalt eller i `.git/info/exclude`. Ikke alle bruker VSCode :)

**Comment by henninghalv** [comment]
Den er god!
Lagde .gitignore_global personlig i hvert fall
