### ISSUE TITLE
Mobil-meny fungerer ikke uten javascript

### ISSUE THREAD

**Issue by ludvigsj** [laafte/lafteweb#6]
Om man ikke har javascript slått på får man ikke tilgang til menyen på mobil. Dette er uheldig, veldig lett å bare ha en fast åpen meny på mobil om man ikke har js.

**Comment by henninghalv** [comment]
Hvis vi ikke har js får vi heller ikke hentet kontaktinfo. Dette gjelder også for #8. Skal vi anta at alle har js?

**Comment by ludvigsj** [comment]
Dette har jeg vel også fikset. Kommer tilbake her også

**Comment by ludvigsj** [comment]
Fikset i 01e080dc16d6f47034bb4b17bb60ff888aa9ab42, 625d58a356a0ddbade67bbcb863a1633882c93b8 og d2b33321f1a4b43a1caa1613c09586f219a4d699
