### ISSUE TITLE
Hoppende pil avhengig av javascript

### ISSUE THREAD

**Issue by ludvigsj** [laafte/lafteweb#8]
Uten javascript vil den hoppende pilen ikke alltid synes. Anbefaler å se på `position: sticky;` i kombinasjon med `bottom`, se om det kan løses bedre.

**Comment by henninghalv** [comment]
Min pil hopper og fungerer fortsatt selvom jeg skrur av js i chrome, men kanskje dette ikke er tilstrekkelig test. Det som ikke fungerer er scroll-animasjonen.

**Comment by ludvigsj** [comment]
Nei altså poenget mitt er at den hopper fint og fungerer fint, MEN siden den er langt ned i den logo-container-tingen som er satt til 100% høyde må man skrolle ned til den i enkelte tilfeller jeg har opplevd. Har fiksa dette tror jeg, kommer tilbake til deg

**Comment by ludvigsj** [comment]
Fikset i 043e446bd8bc48c5285bc9b78c606ec2e083ef73 og 301e384289f48c6ab6816762d34b99c2f2feeefd
